#version 430

uniform float timeScale;

struct Particle{
    vec4 pos;
    vec4 vel;
};

layout(std430, binding = 0) buffer particleBuffer
{
	Particle particles[];
};

layout (local_size_x = 1024, local_size_y = 1) in;
void main() {
	uint i = gl_GlobalInvocationID.x;

	vec4 d = -particles[i].pos;

	float r = length(d);
	float force = (6.67384e-11 * 10E04) / (r*r);
	particles[i].vel += d * force * timeScale / r;

	particles[i].pos += particles[i].vel * timeScale;
}
